
export const data = [
    {
        "storeProductId": 1764,
        "productId": 1,
        "pname": "Fresh Tomato",
        "pUnit": "1Kg",
        "pimage": "http://www.way2door.com/images/products/tamato.jpg",
        "pdescription": "",
        "price": 60,
        "sellPrice": 50,
        "availableQuanity": 0,
        "is_available": 1,
        "mainCat": "Fresh_Vegetables",
        "subMainCat": null,
        "subCat": null,
        "is_active": 1,
        "featured_product": 1,
        "storeId": 26,
        "created_at": "2018-09-09 18:11:45",
        "updated_at": "2021-11-13 15:04:07",
        "deliveryCharge": 40,
        "storeName": "Lucknow Veg Express",
        "freeDeliveryMinOrderAmount": 500,
        "quantity":0
    },
    {
        "storeProductId": 1765,
        "productId": 2,
        "pname": "Potato Old",
        "pUnit": "1 Kg",
        "pimage": "http://www.way2door.com/images/products/potato.jpg",
        "pdescription": "",
        "price": 30,
        "sellPrice": 20,
        "availableQuanity": 0,
        "is_available": 1,
        "mainCat": "Fresh_Vegetables",
        "subMainCat": null,
        "subCat": null,
        "is_active": 1,
        "featured_product": 1,
        "storeId": 26,
        "created_at": "2018-09-09 18:11:45",
        "updated_at": "2021-11-13 15:04:08",
        "deliveryCharge": 40,
        "storeName": "Lucknow Veg Express",
        "freeDeliveryMinOrderAmount": 500,
        "quantity":0
    },
    {
        "storeProductId": 1766,
        "productId": 3,
        "pname": "Onion",
        "pUnit": "1Kg",
        "pimage": "http://www.way2door.com/images/products/onion.jpg",
        "pdescription": "",
        "price": 50,
        "sellPrice": 30,
        "availableQuanity": 0,
        "is_available": 1,
        "mainCat": "Fresh_Vegetables",
        "subMainCat": null,
        "subCat": null,
        "is_active": 1,
        "featured_product": 1,
        "storeId": 26,
        "created_at": "2018-09-09 18:11:45",
        "updated_at": "2021-11-13 15:04:09",
        "deliveryCharge": 40,
        "storeName": "Lucknow Veg Express",
        "freeDeliveryMinOrderAmount": 500,
        "quantity":0
    },
    {
        "storeProductId": 1774,
        "productId": 315,
        "pname": "Green Chilli",
        "pUnit": "250 gm",
        "pimage": "http://www.way2door.com/AllProducts/fruits_and_vegetables/Green Chilli.jpg",
        "pdescription": "",
        "price": 20,
        "sellPrice": 15,
        "availableQuanity": 0,
        "is_available": 1,
        "mainCat": "Fresh_Vegetables",
        "subMainCat": null,
        "subCat": null,
        "is_active": 1,
        "featured_product": 1,
        "storeId": 26,
        "created_at": "2018-09-09 18:38:05",
        "updated_at": "2021-11-13 17:24:04",
        "deliveryCharge": 40,
        "storeName": "Lucknow Veg Express",
        "freeDeliveryMinOrderAmount": 500,
        "quantity":0
    },
    {
        "storeProductId": 1777,
        "productId": 8,
        "pname": "Garlic (Lehsun)",
        "pUnit": "250 gm",
        "pimage": "http://www.way2door.com/images/products/garlic_lehsun.jpg",
        "pdescription": "",
        "price": 60,
        "sellPrice": 40,
        "availableQuanity": 0,
        "is_available": 0,
        "mainCat": "Fresh_Vegetables",
        "subMainCat": null,
        "subCat": null,
        "is_active": 1,
        "featured_product": 1,
        "storeId": 26,
        "created_at": "2018-09-09 18:39:58",
        "updated_at": "2021-11-13 17:28:47",
        "deliveryCharge": 40,
        "storeName": "Lucknow Veg Express",
        "freeDeliveryMinOrderAmount": 500,
        "quantity":0
    },
    {
        "storeProductId": 1779,
        "productId": 334,
        "pname": "Shimla Mirch",
        "pUnit": "250 gm",
        "pimage": "http://www.way2door.com/AllProducts/fruits_and_vegetables/Green Capsicum-way2door.jpg",
        "pdescription": "",
        "price": 40,
        "sellPrice": 20,
        "availableQuanity": 0,
        "is_available": 1,
        "mainCat": "Fresh_Vegetables",
        "subMainCat": null,
        "subCat": null,
        "is_active": 1,
        "featured_product": 1,
        "storeId": 26,
        "created_at": "2018-09-09 18:42:05",
        "updated_at": "2021-11-13 17:24:09",
        "deliveryCharge": 40,
        "storeName": "Lucknow Veg Express",
        "freeDeliveryMinOrderAmount": 500,
        "quantity":0
    },
    {
        "storeProductId": 1782,
        "productId": 327,
        "pname": "Carrot",
        "pUnit": "1 Kg",
        "pimage": "http://www.way2door.com/AllProducts/fruits_and_vegetables/Orange Carrot-way2door.jpg",
        "pdescription": "",
        "price": 50,
        "sellPrice": 40,
        "availableQuanity": 0,
        "is_available": 1,
        "mainCat": "Fresh_Vegetables",
        "subMainCat": null,
        "subCat": null,
        "is_active": 1,
        "featured_product": 1,
        "storeId": 26,
        "created_at": "2018-09-09 18:44:37",
        "updated_at": "2021-11-13 17:27:07",
        "deliveryCharge": 40,
        "storeName": "Lucknow Veg Express",
        "freeDeliveryMinOrderAmount": 500,
        "quantity":0
    },
    {
        "storeProductId": 1788,
        "productId": 9,
        "pname": "Coriander",
        "pUnit": "250 gm",
        "pimage": "http://www.way2door.com/images/products/coriander.jpg",
        "pdescription": "",
        "price": 30,
        "sellPrice": 10,
        "availableQuanity": 0,
        "is_available": 0,
        "mainCat": "Fresh_Vegetables",
        "subMainCat": null,
        "subCat": null,
        "is_active": 1,
        "featured_product": 1,
        "storeId": 26,
        "created_at": "2018-09-09 18:46:49",
        "updated_at": "2021-11-13 17:24:16",
        "deliveryCharge": 40,
        "storeName": "Lucknow Veg Express",
        "freeDeliveryMinOrderAmount": 500,
        "quantity":0
    },
    {
        "storeProductId": 1793,
        "productId": 175,
        "pname": "Pomegranate (Anaar)",
        "pUnit": "1 Kg",
        "pimage": "http://www.way2door.com/AllProducts/fruits_and_vegetables/Pomegranate (Anaar).jpg",
        "pdescription": "",
        "price": 180,
        "sellPrice": 155,
        "availableQuanity": 0,
        "is_available": 1,
        "mainCat": "Fresh_Fruits",
        "subMainCat": null,
        "subCat": null,
        "is_active": 1,
        "featured_product": 1,
        "storeId": 26,
        "created_at": "2018-09-09 18:50:31",
        "updated_at": "2021-11-13 04:21:22",
        "deliveryCharge": 40,
        "storeName": "Lucknow Veg Express",
        "freeDeliveryMinOrderAmount": 500,
        "quantity":0
    },
    {
        "storeProductId": 1800,
        "productId": 39,
        "pname": "Cabbage",
        "pUnit": "1 unit",
        "pimage": "http://www.way2door.com/AllProducts/fruits_and_vegetables/Cabbage-way2door.jpg",
        "pdescription": "",
        "price": 35,
        "sellPrice": 30,
        "availableQuanity": 0,
        "is_available": 1,
        "mainCat": "Fresh_Vegetables",
        "subMainCat": null,
        "subCat": null,
        "is_active": 1,
        "featured_product": 1,
        "storeId": 26,
        "created_at": "2018-09-09 19:06:49",
        "updated_at": "2021-11-13 17:34:35",
        "deliveryCharge": 40,
        "storeName": "Lucknow Veg Express",
        "freeDeliveryMinOrderAmount": 500,
        "quantity":0
    },
    {
        "storeProductId": 1802,
        "productId": 66,
        "pname": "Cauliflower",
        "pUnit": "1 unit",
        "pimage": "http://www.way2door.com/AllProducts/fruits_and_vegetables/Cauliflower.jpg",
        "pdescription": "",
        "price": 50,
        "sellPrice": 30,
        "availableQuanity": 0,
        "is_available": 1,
        "mainCat": "Fresh_Vegetables",
        "subMainCat": null,
        "subCat": null,
        "is_active": 1,
        "featured_product": 1,
        "storeId": 26,
        "created_at": "2018-09-09 19:07:19",
        "updated_at": "2021-11-13 17:34:21",
        "deliveryCharge": 40,
        "storeName": "Lucknow Veg Express",
        "freeDeliveryMinOrderAmount": 500,
        "quantity":0
    },
    {
        "storeProductId": 1811,
        "productId": 34,
        "pname": "Guava ( Amrud )",
        "pUnit": "1Kg",
        "pimage": "http://www.way2door.com/AllProducts/fruits_and_vegetables/Guava.jpg",
        "pdescription": "",
        "price": 65,
        "sellPrice": 60,
        "availableQuanity": 0,
        "is_available": 1,
        "mainCat": "Fresh_Fruits",
        "subMainCat": null,
        "subCat": null,
        "is_active": 1,
        "featured_product": 1,
        "storeId": 26,
        "created_at": "2018-09-10 14:38:48",
        "updated_at": "2021-11-13 04:30:33",
        "deliveryCharge": 40,
        "storeName": "Lucknow Veg Express",
        "freeDeliveryMinOrderAmount": 500,
        "quantity":0
    },
    {
        "storeProductId": 1816,
        "productId": 30,
        "pname": "Papaya 1 KG",
        "pUnit": "1 unit",
        "pimage": "http://www.way2door.com/AllProducts/fruits_and_vegetables/Papaya-way2door.jpg",
        "pdescription": "",
        "price": 60,
        "sellPrice": 55,
        "availableQuanity": 0,
        "is_available": 1,
        "mainCat": "Fresh_Fruits",
        "subMainCat": null,
        "subCat": null,
        "is_active": 1,
        "featured_product": 1,
        "storeId": 26,
        "created_at": "2018-09-10 14:39:19",
        "updated_at": "2021-11-13 04:16:48",
        "deliveryCharge": 40,
        "storeName": "Lucknow Veg Express",
        "freeDeliveryMinOrderAmount": 500,
        "quantity":0
    },
    {
        "storeProductId": 1819,
        "productId": 224,
        "pname": "Milk",
        "pUnit": "1 unit",
        "pimage": "https://www.bigbasket.com/media/uploads/p/m/40005033_1-amul-moti-homogenised-toned-milk.jpg?tr=w-1080,q=80",
        "pdescription": "",
        "price": 50,
        "sellPrice": 40,
        "availableQuanity": 0,
        "is_available": 0,
        "mainCat": "dairy",
        "subMainCat": null,
        "subCat": null,
        "is_active": 1,
        "featured_product": 1,
        "storeId": 26,
        "created_at": "2018-09-10 14:56:49",
        "updated_at": "2021-11-13 04:39:42",
        "deliveryCharge": 40,
        "storeName": "Lucknow Veg Express",
        "freeDeliveryMinOrderAmount": 500,
        "quantity":0
    },
    {
        "storeProductId": 2608,
        "productId": 229,
        "pname": "Banana",
        "pUnit": "12 unit",
        "pimage": "http://www.way2door.com/AllProducts/fruits_and_vegetables/Yellaki (Kathali Kala) Banana-way@door.jpg",
        "pdescription": "",
        "price": 60,
        "sellPrice": 50,
        "availableQuanity": 0,
        "is_available": 1,
        "mainCat": "Fresh_Fruits",
        "subMainCat": null,
        "subCat": null,
        "is_active": 1,
        "featured_product": 1,
        "storeId": 26,
        "created_at": "2021-11-13 04:27:13",
        "updated_at": "2021-11-13 04:28:16",
        "deliveryCharge": 40,
        "storeName": "Lucknow Veg Express",
        "freeDeliveryMinOrderAmount": 500,
        "quantity":0
    },
    {
        "storeProductId": 2609,
        "productId": 25,
        "pname": "fish",
        "pUnit": "1 Kg",
        "pimage": "https://s3-ap-southeast-1.amazonaws.com/cashback-static/upload/files/2020-09-22/11ec5dab5fe0b7694d515907eace4306.jpg",
        "pdescription": "",
        "price": 140,
        "sellPrice": 130,
        "availableQuanity": 1,
        "is_available": 1,
        "mainCat": "non_veg",
        "subMainCat": null,
        "subCat": null,
        "is_active": 1,
        "featured_product": 1,
        "storeId": 26,
        "created_at": "2021-11-13 04:31:52",
        "updated_at": "2021-11-13 04:32:29",
        "deliveryCharge": 40,
        "storeName": "Lucknow Veg Express",
        "freeDeliveryMinOrderAmount": 500,
        "quantity":0
    },
    {
        "storeProductId": 2610,
        "productId": 171,
        "pname": "Almonds",
        "pUnit": "1 Kg",
        "pimage": "https://www.bigbasket.com/media/uploads/p/m/40232836_2-tata-sampann-100-pure-california-almonds-flavourful-deluxe-size.jpg?tr=w-1080,q=80",
        "pdescription": "",
        "price": 170,
        "sellPrice": 165,
        "availableQuanity": 1,
        "is_available": 1,
        "mainCat": "dry_fruits",
        "subMainCat": null,
        "subCat": null,
        "is_active": 1,
        "featured_product": 1,
        "storeId": 26,
        "created_at": "2021-11-13 04:31:52",
        "updated_at": "2021-11-13 04:32:30",
        "deliveryCharge": 40,
        "storeName": "Lucknow Veg Express",
        "freeDeliveryMinOrderAmount": 500,
        "quantity":0
    }
]